#!/bin/bash
set -euo pipefail

if [ ! -f ".env.example" ]; then
    echo "Nu găsesc .env.example în $(pwd)" >&2
    exit 1
fi

echo "========================================="
echo " Configurator .env pentru Expense Bot AI"
echo "========================================="
echo ""

read -p "Domeniul principal (ex: domeniu.com): " PRIMARY_DOMAIN
PRIMARY_DOMAIN=${PRIMARY_DOMAIN,,}

if [ -z "$PRIMARY_DOMAIN" ]; then
    echo "Domeniul este obligatoriu." >&2
    exit 1
fi

read -p "Folosești același domeniu pentru interfața web? [Y/n]: " SAME_DOMAIN
SAME_DOMAIN=${SAME_DOMAIN:-Y}

if [[ "$SAME_DOMAIN" =~ ^[Nn]$ ]]; then
    read -p "Domeniu separat pentru web (ex: app.domeniu.com): " WEB_DOMAIN
    WEB_DOMAIN=${WEB_DOMAIN,,}
    if [ -z "$WEB_DOMAIN" ]; then
        echo "Domeniul web nu poate fi gol." >&2
        exit 1
    fi
else
    WEB_DOMAIN=$PRIMARY_DOMAIN
fi

read -p "Email pentru Let's Encrypt (alerte SSL): " SSL_EMAIL
if [ -z "$SSL_EMAIL" ]; then
    echo "Email-ul este obligatoriu." >&2
    exit 1
fi

read -p "IP-ul public al serverului (opțional): " SERVER_IP

read -s -p "Groq API key: " GROQ_KEY
echo ""
if [ -z "$GROQ_KEY" ]; then
    echo "Groq API key este obligatorie." >&2
    exit 1
fi

read -s -p "Telegram Bot Token: " TELEGRAM_TOKEN
echo ""
if [ -z "$TELEGRAM_TOKEN" ]; then
    echo "Telegram Bot Token este obligatoriu." >&2
    exit 1
fi

read -s -p "Parola pentru Postgres (Enter pentru auto-gen): " DB_PASSWORD
echo ""
if [ -z "$DB_PASSWORD" ]; then
    DB_PASSWORD=$(python3 - <<'PY'
import secrets, string
alphabet = string.ascii_letters + string.digits
print(''.join(secrets.choice(alphabet) for _ in range(20)))
PY
)
    echo "→ Parolă Postgres generată automat."
fi

read -s -p "Cheie ENCRYPTION (hex 64 chars, Enter pentru auto-gen): " ENCRYPTION_KEY
echo ""
if [ -z "$ENCRYPTION_KEY" ]; then
    ENCRYPTION_KEY=$(python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
)
    echo "→ ENCRYPTION_KEY generată automat."
fi

read -s -p "JWT secret (Enter pentru auto-gen): " JWT_SECRET
echo ""
if [ -z "$JWT_SECRET" ]; then
    JWT_SECRET=$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(48))
PY
)
    echo "→ JWT secret generat automat."
fi

DEFAULT_USER_ID="00000000-0000-0000-0000-000000000001"
NEXT_PUBLIC_API_URL="https://${PRIMARY_DOMAIN}/api"

cat > .env <<EOF
# ===================================
# Generated by scripts/bootstrap_env.sh on $(date)
# ===================================

# AI Service
GROQAPIKEY=${GROQ_KEY}
GROQ_API_KEY=${GROQ_KEY}

# Telegram Bot
telegramToken=${TELEGRAM_TOKEN}
TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}

# Database Configuration
DATABASE_URL=postgresql://expenseuser:${DB_PASSWORD}@db:5432/expensebot
DB_USER=expenseuser
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=expensebot

# Redis
REDIS_URL=redis://redis:6379

# Encryption / Auth
ENCRYPTION_KEY=${ENCRYPTION_KEY}
JWT_SECRET_KEY=${JWT_SECRET}
JWT_ALGORITHM=HS256
JWT_EXPIRATION_HOURS=24
DEFAULT_USER_ID=${DEFAULT_USER_ID}

# Access Control (customize dacă e nevoie)
ALLOWED_GROUP_ID=
ALLOWED_USER_IDS=

# Domains / URLs
DOMAIN=${PRIMARY_DOMAIN}
WEB_DOMAIN=${WEB_DOMAIN}
SERVER_IP=${SERVER_IP}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
API_BASE_URL=http://app:8000
ADDITIONAL_CORS_ORIGINS=

# SSL
SSL_EMAIL=${SSL_EMAIL}

# Application
APP_PORT=8000
LOG_LEVEL=info
EOF

echo ""
echo "========================================="
echo " .env a fost generat cu succes!"
echo " - Domeniu API: https://${PRIMARY_DOMAIN}/api"
echo " - Domeniu Web: https://${WEB_DOMAIN}"
echo "Continuă cu:"
echo "  1. ./setup-ssl.sh"
echo "  2. docker-compose -f docker-compose.prod.yml up -d"
echo "========================================="
